### ISSUE TITLE
?

### ISSUE THREAD

**Issue by 700montes** [LuXuryCheats/sdk.solutions-fn-external#1]
why sell my old external source? i leaked on github like 6 months ago why even sell LOL...
https://nigga.ltd/x/oracle-updated

**Comment by LuXuryCheats** [comment]
> why sell my old external source? i leaked on github like 6 months ago why even sell LOL...
> https://nigga.ltd/x/oracle-updated

**if it wasnt obvious its fake.**, and why are you stalking my github page lmfao.

**Comment by LuXuryCheats** [comment]
> why sell my old external source? i leaked on github like 6 months ago why even sell LOL...
> https://nigga.ltd/x/oracle-updated

i never even pasted this source it was given to me for free?

**Comment by 700montes** [comment]
> > why sell my old external source? i leaked on github like 6 months ago why even sell LOL...
> > https://nigga.ltd/x/oracle-updated
> 
> **if it wasnt obvious its fake.**, and why are you stalking my github page lmfao.

why make a repo if its fake then

**Comment by LuXuryCheats** [comment]
> > > why sell my old external source? i leaked on github like 6 months ago why even sell LOL...
> > > https://nigga.ltd/x/oracle-updated
> > 
> > 
> > **if it wasnt obvious its fake.**, and why are you stalking my github page lmfao.
> 
> why make a repo if its fake then

because it was a joke so i could get friends because im so lonely
